#!/usr/bin/env bash

link="<p><a href='https://github.com/timm/slip'>src</a></p>"

for f in "$1"/*.html; do
  gawk -v l="$link" '
    $0 ~ /<div class=.docs.><h1>/ {
      sub(/<div class=.docs.><h1>/, "")
      print "<div class=\"docs\">" l "<h1>" $0
      next
    }
    1' "$f" > "$f.tmp"
  mv "$f.tmp" "$f"
done
